version: '3.4'

services:
  backend:
    container_name: backend
    image: ${DOCKER_REGISTRY-}intermediarysearchserviceapi
    depends_on:
        - postgres
    build:
      context: .
      dockerfile: src/IntermediarySearchService.Api/Dockerfile

  #client:
  #  container_name: client
  #  image: client
  #  build:
  #    context: ./frontend-app
  #    dockerfile: Dockerfile

  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_USER: "root_user"
      POSTGRES_PASSWORD: "pass12345"
      PGDATA: "/data/pgdata"
    ports:
      - "5432:5432"
    volumes:
       - postgres:/data/postgres

volumes:
  postgres:
